# Generated by Django 4.1.3 on 2022-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='571*87Q54)76[46B59<905', max_length=300, null=True),
        ),
    ]
