# Generated by Django 4.1.3 on 2022-11-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0002_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='L71$58J39N89:87M37>83,', max_length=300, null=True),
        ),
    ]
