# Generated by Django 4.1.3 on 2022-11-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0003_appuserprofile_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='491*47[75I90)40250C717', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
