# Generated by Django 4.1.3 on 2022-11-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0006_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='671?42X64C62487450L74S', max_length=300, null=True),
        ),
    ]
