# Generated by Django 4.1.3 on 2022-11-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0007_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='L71N64T45?81U59G43765/', max_length=300, null=True),
        ),
    ]
