# Generated by Django 4.1.3 on 2022-11-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0008_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='A83,46791K68382V44)68N', max_length=300, null=True),
        ),
    ]
