# Generated by Django 4.1.3 on 2022-11-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0009_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='M83*68%90G74G76E84H82,', max_length=300, null=True),
        ),
    ]
