# Generated by Django 4.1.3 on 2022-11-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0010_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default=':74O84>61U73G77=41H55W', max_length=300, null=True),
        ),
    ]
