# Generated by Django 4.1.3 on 2022-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0011_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='%71/72;70674=82N72W73I', max_length=300, null=True),
        ),
    ]
