# Generated by Django 4.1.3 on 2022-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0013_alter_appuserprofile_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycards',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/app_user/{profile}'),
        ),
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='C87S43349U38I90&66#61B', max_length=300, null=True),
        ),
    ]
