# Generated by Django 4.1.3 on 2022-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0015_mycards_code_alter_appuserprofile_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='D41X87564@56<80+63P80A', max_length=300, null=True),
        ),
    ]
