# Generated by Django 4.1.3 on 2022-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0016_alter_appuserprofile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='V65F73681@60B48.34Z84#', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/app_user'),
        ),
    ]
