# Generated by Django 4.1.3 on 2022-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0018_alter_appuserprofile_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='167753:65D87<53F57C64B', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/app_user'),
        ),
    ]
