# Generated by Django 4.1.3 on 2022-11-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0020_alter_appuserprofile_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='D83;74>67J71K65U79(63H', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/app_user/%y/%m/%d'),
        ),
    ]
