# Generated by Django 4.1.3 on 2022-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0021_alter_appuserprofile_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='G65?74G46=44N57972*48<', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='app_user'),
        ),
    ]
