# Generated by Django 4.1.3 on 2022-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0022_alter_appuserprofile_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='Q35@79684I69465L49X57(', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/app_user/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mycards',
            name='image',
            field=models.ImageField(blank=True, upload_to='mycards'),
        ),
    ]
