# Generated by Django 4.1.3 on 2022-12-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0023_alter_appuserprofile_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='confirmation',
            field=models.CharField(default='R74289+60#67G86:34#43L', max_length=300, null=True),
        ),
    ]
