# Generated by Django 4.1.3 on 2022-11-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_alter_businesses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
