# Generated by Django 4.1.3 on 2022-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_businesses_active_cards_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
