# Generated by Django 4.1.3 on 2022-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_remove_businesses_email_alter_businesses_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
