# Generated by Django 4.1.3 on 2022-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_alter_businesses_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default="539C79A90'34*80:56E87>", max_length=300, null=True),
        ),
    ]
