# Generated by Django 4.1.3 on 2022-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_profile_slug_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='Q85.86044486>59Y401393', max_length=300, null=True),
        ),
    ]
