# Generated by Django 4.1.3 on 2022-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0011_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default="'43E73:41.51Y45889Z36G", max_length=300, null=True),
        ),
    ]
