# Generated by Django 4.1.3 on 2022-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0012_businesses_business_name_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default="H48B47&75%74'77.37R76>", max_length=300, null=True),
        ),
    ]
