# Generated by Django 4.1.3 on 2022-11-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0014_alter_businesses_slug_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='slug',
            field=models.SlugField(blank=True, default='P59490983@37[46A50B51N', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='D35O66S39X55*37Q83K81Y', max_length=300, null=True),
        ),
    ]
