# Generated by Django 4.1.3 on 2022-11-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0017_alter_businesses_slug_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='>63&53)60@64369682)80M', max_length=300, null=True),
        ),
    ]
