# Generated by Django 4.1.3 on 2022-11-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0019_alter_businesses_slug_alter_profile_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='slug',
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default="L54G53&43(41G64Y50[64'", max_length=300, null=True),
        ),
    ]
