# Generated by Django 4.1.3 on 2022-11-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0022_alter_profile_confirmation_alter_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='I50654Q89%44779&60,44=', max_length=300, null=True),
        ),
    ]
