# Generated by Django 4.1.3 on 2022-11-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0025_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default="L56'44#37)45480Z35L681", max_length=300, null=True),
        ),
    ]
