# Generated by Django 4.1.3 on 2022-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0026_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesses',
            name='long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='L90&78F64436R63045K71=', max_length=300, null=True),
        ),
    ]
