# Generated by Django 4.1.3 on 2022-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0027_businesses_lat_businesses_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='D69A37C50K89;51H35I477', max_length=300, null=True),
        ),
    ]
