# Generated by Django 4.1.3 on 2022-11-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0029_alter_businesses_slug_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='business_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default=';86J89\'90277+90)75"37G', max_length=300, null=True),
        ),
    ]
