# Generated by Django 4.1.3 on 2022-11-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0030_alter_businesses_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='>46#58L77;69O58)64Z41U', max_length=300, null=True),
        ),
    ]
