# Generated by Django 4.1.3 on 2022-11-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0031_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='480874C90P83+79Z40?63N', max_length=300, null=True),
        ),
    ]
