# Generated by Django 4.1.3 on 2022-11-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0032_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='K85852V88Q42,72789591X', max_length=300, null=True),
        ),
    ]
