# Generated by Django 4.1.3 on 2022-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0033_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='$42,75V57Z72T47V75K582', max_length=300, null=True),
        ),
    ]
