# Generated by Django 4.1.3 on 2022-11-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0036_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='$71847548,43I41D70,73C', max_length=300, null=True),
        ),
    ]
