# Generated by Django 4.1.3 on 2022-11-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0037_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='T81644Q74X41D51T49950M', max_length=300, null=True),
        ),
    ]
