# Generated by Django 4.1.3 on 2022-11-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0038_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default="'65V66*44.52>73964?37,", max_length=300, null=True),
        ),
    ]
