# Generated by Django 4.1.3 on 2022-11-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0039_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='653$60/62/51G53#74"66I', max_length=300, null=True),
        ),
    ]
