# Generated by Django 4.1.3 on 2022-11-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0041_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='+86-51#46O89)34#44<53@', max_length=300, null=True),
        ),
    ]
