# Generated by Django 4.1.3 on 2022-11-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0042_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='Z65X44A64G76U38$39)46"', max_length=300, null=True),
        ),
    ]
