# Generated by Django 4.1.3 on 2022-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0043_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='D76W62G59F90Z55#51D62T', max_length=300, null=True),
        ),
    ]
