# Generated by Django 4.1.3 on 2022-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0044_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='Y75C74K52A56%39949H59.', max_length=300, null=True),
        ),
    ]
