# Generated by Django 4.1.3 on 2022-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0045_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='+72151A52E81476)54135X', max_length=300, null=True),
        ),
    ]
