# Generated by Django 4.1.3 on 2022-11-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0046_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='M74.81645&81?77043I82U', max_length=300, null=True),
        ),
    ]
