# Generated by Django 4.1.3 on 2022-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0047_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='.45N80.71*55Y49U38362J', max_length=300, null=True),
        ),
    ]
