# Generated by Django 4.1.3 on 2022-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0048_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='540@50X87B54T42/43@682', max_length=300, null=True),
        ),
    ]
