# Generated by Django 4.1.3 on 2022-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0050_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='V85960=38S44E57O36C74X', max_length=300, null=True),
        ),
    ]
