# Generated by Django 4.1.3 on 2022-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0051_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='E91735.59Z84S42@45I84J', max_length=300, null=True),
        ),
    ]
