# Generated by Django 4.1.3 on 2022-11-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0052_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='#44"37/61O89N51.81072P', max_length=300, null=True),
        ),
    ]
