# Generated by Django 4.1.3 on 2022-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0053_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='990E52254P49?51)34,494', max_length=300, null=True),
        ),
    ]
