# Generated by Django 4.1.3 on 2022-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0054_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default="679O86J64'35N59#89;77?", max_length=300, null=True),
        ),
    ]
