# Generated by Django 4.1.3 on 2022-12-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0055_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='<81J83A62J62W88082Y75F', max_length=300, null=True),
        ),
    ]
