# Generated by Django 4.1.3 on 2022-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0056_alter_profile_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(default='C80U76Q78"35P90+45/79P', max_length=300, null=True),
        ),
    ]
